-- Migration: Create custom_scrapers table for BYOS

CREATE TABLE IF NOT EXISTS custom_scrapers (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references workspaces(id) on delete cascade,
    platform text not null,
    api_key text,
    api_host text not null,
    search_endpoint text not null,
    search_param_name text not null,
    comments_endpoint text,
    comments_param_name text,
    items_json_path text not null,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    unique(workspace_id, platform)
);

-- RLS
alter table custom_scrapers enable row level security;

create policy "Users can view scrapers for their workspaces"
    on custom_scrapers for select
    using (
        workspace_id in (
            select workspace_id from workspace_members 
            where user_id = auth.uid()
        )
    );

create policy "Users can insert scrapers for their workspaces"
    on custom_scrapers for insert
    with check (
        workspace_id in (
            select workspace_id from workspace_members 
            where user_id = auth.uid()
        )
    );

create policy "Users can update their workspace scrapers"
    on custom_scrapers for update
    using (
        workspace_id in (
            select workspace_id from workspace_members 
            where user_id = auth.uid()
        )
    );

create policy "Users can delete their workspace scrapers"
    on custom_scrapers for delete
    using (
        workspace_id in (
            select workspace_id from workspace_members 
            where user_id = auth.uid()
        )
    );

-- Trigger for updated_at
create trigger set_custom_scrapers_updated_at
    before update on custom_scrapers
    for each row
    execute function update_modified_column();